### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by GoncaloOlas** [GoncaloOlas/myBuzzer#1]
- [x] Maximize on start screen, minimize when started and maximize when finished (1 screen, no timer just max and min) 
- [x] Make it appear in front of whatever in the beginning
- [x] Make it center
- [x] Make it pop up when the 90 minutes are over
- [x] Make it run for 90 min (uncomment time.sleep(1)) and alter to minutes < 90)
